version: "3.6"

services:
  account:
    build:
      context: "."
      dockerfile: "./account/app.dockerfile"
    depends_on:
      - "account_db"
    environment:
      DATABASE_URL: "postgres://grab:123456@account_db/grab?sslmode=disable"

  catalog:
    build:
      context: "."
      dockerfile: "./catalog/app.dockerfile"
    depends_on:
      - "catalog_db"
    environment:
      DATABASE_URL: "http://catalog_db:9200"

  order:
    build:
      context: "."
      dockerfile: "./order/app.dockerfile"
    depends_on:
      - "order_db"
    environment:
      DATABASE_URL: "postgres://grab:123456@order_db/grab?sslmode=disable"
      ACCOUNT_SERVICE_URL: "account:8080"
      CATALOG_SERVICE_URL: "catalog:8080"

  graphql:
    build:
      context: "."
      dockerfile: "./graphql/app.dockerfile"
    ports:
      - "8000:8080"
    depends_on:
      - "account"
      - "catalog"
    environment:
      ACCOUNT_SERVICE_URL: "account:8080"
      CATALOG_SERVICE_URL: "catalog:8080"
      ORDER_SERVICE_URL: "order:8080"

  account_db:
    build:
      context: "./account"
      dockerfile: "./db.dockerfile"
    environment:
      POSTGRES_DB: "grab"
      POSTGRES_USER: "grab"
      POSTGRES_PASSWORD: "123456"
    restart: "unless-stopped"

  catalog_db:
    image: "docker.elastic.co/elasticsearch/elasticsearch:6.2.4"
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
      discovery.type: "single-node"

  order_db:
    build:
      context: "./order"
      dockerfile: "./db.dockerfile"
    environment:
      POSTGRES_DB: "grab"
      POSTGRES_USER: "grab"
      POSTGRES_PASSWORD: "123456"
    restart: "unless-stopped"
